baseapp/pom.xml, gateway-ha/pom.xml, gateway-ha/src/test/java/io/trino/gateway/ha/security/LbLdapClientTest.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbFilter.java, mvnw, pom.xml, proxyserver/pom.xml
This updates the source and target Java versions to 17. Tests currently failing on `main` with Java 11 are disabled by this PR.
=> Update Java version to 17

baseapp/pom.xml, gateway-ha/pom.xml, pom.xml, proxyserver/pom.xml
So that we can later release version 3 (which is higher than 1.9.5 from original project and 2.x used at some current users) and avoid the whole semantic version idea and follow the same pattern as Trino itself.
As discussed with @martint
=> Set version to 3-SNAPSHOT

pom.xml
Our CI run found a first problem .. version was hardcoded in the dependencyMgt section. This fixes the problem and should get us back to a passing CI.
=> Fix internal project dependency

.mvn/jvm.config, gateway-ha/pom.xml, mvnw
This allows the build to succeed using `mvn install` instead of requiring `./mvnw install`
=> Move VM options to jvm.config

gateway-ha/pom.xml
- Open package access for integration tests
- Add note about same content in jvm.config
This reinstates a setting we moved into jvm.config since surefire can not pick it up. Brings the build back to passing. 
Please review and chime in @willmostly 
Once we adopt airbase this will move again to use the property
air.test.jvm.additional-arguments
=> Add JVM config for test runs

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java
Allow gateway to route `v1/node` that returns node info. 
- We use this to API to find all workers address, then request `{worker_addr}/v1/status` to find cpu/memory stats.
=> Allow /v1/node to be routed by gateway

docs/security.md
- odic -> OAuth/OpenIDConnect
- `odic` is typo for `oidc` which means OpenIDConnect
- Conf is set using OAuth so added example to set defaultType as OAuth to use OIDC/OAuth
- Separated `Form` into `basic auth` and `LDAP auth`
- I haven't tested LDAP conf yet, but [FormConfiguration code](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/config/FormAuthConfiguration.java) has LDAP as string type so I just added simple guide
- `privateKeyRsa` and `publicKeyRsa` had should have R`sa` as lowercase
- [keypair is read as file, not string](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/security/LbKeyProvider.java#L35-L53)
=> Improve security documentation

.github/CONTRIBUTING.md, README.md, docs/development.md
=> Add doc for contributing

baseapp/pom.xml, gateway-ha/pom.xml, pom.xml, proxyserver/pom.xml
- Add airbase as parent to enable release in future
- Add necessary details for release
- Add airbase property overrides to skip various checks to allow passing build
- Move test code into correct path
- Centralize property declarations in parent pom
- Improve dependency declarations and add version overrides as minimally needed
Fixes #3 
Fixes #14
=> Improve project setup

localdev/docker-compose.yml
Upgrade docker-compose file version
- The `start_period` option was added in file format 3.4
- https://docs.docker.com/compose/compose-file/compose-file-v3/#healthcheck
Specify `PGUSER=trino_gateway_db_admin` in postgresql so that it doesn't use current OS user as database user name. 
- Postgre keeps logging `FATAL:  role "root" does not exist` 
- https://stackoverflow.com/questions/60193781/postgres-with-docker-compose-gives-fatal-role-root-does-not-exist-error/60194261#60194261
Specify `PGDATABASE=trino_gateway_db` so that it doesn't use user name as DB name to access in default.
- `FATAL:  database "trino_gateway_db_admin" does not exist`
Update mysql healthcheck cmd (needs pwd)
- Mysql keeps logging `[Note] Access denied for user 'root'@'localhost' (using password: NO)`
Add support …
=> Fix development environment configs

docs/routing-rules.md
- Simple typo to fix the example where `"` should not exist in the rules
- Add explanation to the logic where if routing-rules config is not set properly, it uses default routing logic (using header)
=> Improve routing rules document

README.md, docs/design.md, docs/development.md, docs/gateway-api.md, docs/operation.md, docs/release-notes.md, docs/resource-groups-api.md, docs/routing-rules.md, docs/security.md
* New page for release notes
* Navigation adjustments
* Content for Trino Gateway 3 release
=> Add release notes for Trino Gateway 3

gateway-ha/pom.xml
This disables javadoc linting and enables source jar creation. Therefore enables release process.
With this I can run
```
./mvnw clean install -P oss-release -Dgpg.skip=true
```
successfully and get source and javadoc jar files.
=> Disable javadoc linting

docs/release-notes.md
@martint seems like whatever we did for testing .. when merged it did not work. When testing this PR I observed that there is quite a delay in github sometimes between a commit arriving and the update of the rendered markdown.
Anyway, I looked up autolinking at https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls and I think the current approach is shortest and seems to work. 
Also note that this branch is in the main repo for testing purposes - https://github.com/trinodb/trino-gateway/blob/release-3/docs/release-notes.md
=> Update release notes for version 3

gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOidcToken.java
We currently have the bare minimum oauth properties supported. Any additional properties in the token result in parsing exception. The scope of the fix is to avoid the exception by ignoring unsupported properties.
=> Ignore the unhandled ODIC properties gracefully

docs/security.md, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbAuthorizer.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthorizer.java
Use regex instead of contains to support more cases where more than 1 type of user members can exist and not all but some of the groups/members are allowed for User role.
=> Use regex expression for authorization

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthorizer.java
This fixes import and signature usage so tests actually compile and run.
=> Fix LbAuthorizer test

gateway-ha/gateway-ha-config.yml, gateway-ha/src/main/java/io/trino/gateway/ha/config/RequestRouterConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, pom.xml, proxyserver/pom.xml, proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServer.java, proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServerConfiguration.java, proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServletImpl.java, proxyserver/src/test/java/io/trino/gateway/proxyserver/TestProxyServer.java
Add dynamic header size config for http server and client
- Idk where to document it. Any ideas?
- https://trinodb.slack.com/archives/C059KUNPTSP/p1695708028907499
Values set in the conf are the default sizes set by Jetty
[HttpConfiguration](https://github.com/eclipse/jetty.project/blob/jetty-9.4.48.v20220622/jetty-server/src/main/java/org/eclipse/jetty/server/HttpConfiguration.java#L61-L64) & [HttpClient](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-client/src/main/java/org/eclipse/jetty/client/HttpClient.java#L142-L143)
```java
// Set size for HttpConfiguration
private int outputBufferSize = 32 * 1024;
private int requestHeaderSize = 8 * 1024;
private int responseHeaderSize = 8 * 1024;
// Set size for HttpClient
private int requestBufferSize = 4 * 1024;
private int …
```
=> add dynamic header size config for http server and client

docs/configuration.md, docs/design.md, docs/development.md, docs/gateway-api.md, docs/operation.md, docs/references.md, docs/release-notes.md, docs/resource-groups-api.md, docs/routing-rules.md, docs/security.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/resources/test-config-template.yml
This submission allows configuring extra paths to proxy without a code change. This is useful for cases in which Trino has been extended to add extra APIs, and cases in which access to one of the paths not whitelisted by default is desired.
=> Add option for extra whitelisted paths

docs/gateway-api.md, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java, proxyserver/pom.xml
I was looking at some [PRs](https://github.com/lyft/presto-gateway/pull/122/files) from lyft/gateway to see any improvements that can be made and noticed that `externalUrl` was not added on create.
If the user wanted to set external url as [Gateway API guide](https://github.com/trinodb/trino-gateway/blob/main/docs/gateway-api.md#add-or-update-a-backend) saids, I need to create add backend, then edit external url.
There was no issue code-wise until now because proxyTo conf (a.k.a backend_url) was used instead of external_url
- https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/config/ProxyBackendConfiguration.java#L16-L21
Also updated docs/gateway-api docs as it has typos/curl syntax issue
FYI. ~Test fails until …
=> Fix bug on create backend to support external URL

gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java
The routing rules engine will reload the rules file if it is newer than the last set of rules, based on the timestamp from the file attributes. However, `java.nio.file.attribute.FileTime` offers a maximum precision of 1 ms. 
We see an intermittent test failure due to a rules file being changed but not reloaded. The theory is that the test writes a new rules file <1ms after the first one, so a 1ms sleep is added to prevent this.
=> Ensure file change is observable

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java
A small fix for a logging format in `QueryIdCachingProxyHandler`.
=> Fixes a wrong logging format in QueryIdCachingProxyHandler

docs/configuration.md, docs/design.md, docs/development.md, docs/gateway-api.md, docs/operation.md, docs/quickstart-config.yaml, docs/quickstart.md, docs/references.md, docs/release-notes.md, docs/resource-groups-api.md, docs/routing-rules.md, docs/security.md
These pages add an example of how to stand up a Trino Gateway locally and add two backends. They are intended as a Quickstart option for someone interested in exploring the Gateway, and not to replace the development enviroment. They were presented in the Fall 2023 Trino Summit.
=> Add quickstart scripts

pom.xml
`air.check.skip-spotbugs` with true is same as Trino repository. 
`air.check.fail-spotbugs` with false leaves noisy error messages.
=> Skip spotbugs instead of false fail-spotbugs

docs/security.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/LdapConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbLdapClient.java, gateway-ha/src/test/resources/auth/ldapTestConfig.yml
Add checking connection before borrowing from the pool for stability.
- In our k8s, unless KA is set for sockets, it cleans up process that has been idle for 10 min.
- So, if the LDAP connection socket is not used and goes idle for more than 10 min, it gets deleted without gateway server knowing that is is invalid.
- Then next time ldapClient borrows the connection and makes request, it fails as log below.
- https://trinodb.slack.com/archives/C059KUNPTSP/p1700796849182119
=> Add check before borrowing from pool

gateway-ha/pom.xml
This is a prerequisite for Java 21 and enables building with Java 21 without requiring Java 21 for runtime.
I am happy for this to be merged now .. and then the original PR requiring Java 21 after at least one Trino Gateway release. That can then also update the Trino JDBC dependency maybe.
=> Add org.mvel:mvel2 dependency

gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java
To address [123](https://github.com/trinodb/trino-gateway/issues/123), we need to first add logging to determine if the file change is detectable by comparing timestamps with millisecond precision.
=> Add logging for flaky test

gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java
Fixes https://github.com/trinodb/trino-gateway/issues/123
=> Fix rule file test

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/TrinoQueueLengthChecker.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueueLengthRoutingTable.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java, pom.xml
Fixes https://github.com/trinodb/trino-gateway/issues/155.
=> Disallow double bracket initialization

gateway-ha/src/main/resources/template/gateway-view.ftl
The `BackendState` went from being `@data` class to be a `record`
=> Fix the Clusters tab rendering

docs/release-notes.md
Assemble the release notes for Trino Gateway 5 release.
Format: maintainer, PR/issue number, ✅ / ❌ rn ✅ / ❌ docs
* #108 ✅ rn ✅ docs
* #93 ✅ rn ✅ docs 
* #104 ✅ rn ✅ docs
* #105 ✅ rn ✅ docs
* #110 ✅ rn ✅ docs
* #112 ✅ rn ✅ docs
* #111 ✅ rn ✅ docs
* #106 ✅ rn ✅ docs
* #115 ✅ rn ✅ docs
* #118 ✅ rn ✅ docs
* #121 ✅ rn ✅ docs
* #124 ✅ rn ✅ docs
* #122 ✅ rn ✅ docs
* #120 ✅ rn ✅ docs
* #126 ✅ rn ✅ docs
* #127 ✅ rn ✅ docs
* #128 ✅ rn ✅ docs
* #129 ✅ rn ✅ docs
* #130 ✅ rn ✅ docs
* #133 ✅ rn ✅ docs
* #136 ✅ rn ✅ …
=> Add release notes for Trino Gateway 5

gateway-ha/pom.xml, pom.xml
Removing configs since they are managed by airbase anyway and we dont want to use these old versions. 
I confirmed that the new setup produces a identical JAR (apart from timestamp and git commit info and irrelevant empty lines in metadata files).
=> Update Maven plugins

.github/bin/retry, .github/workflows/milestone.yml
This is the same flow as used in the trino repo. Should work the same since the pom setup and such are identical. I am not sure if there is a way to test apart from merging it.
Fixes #187
=> Add github milestone labeling

.github/workflows/ci.yml
Fixes https://github.com/trinodb/trino-gateway/issues/197
=> Add CI job for Docker build

README.md, docs/design.md, docs/development.md, docs/gateway-api.md, docs/installation.md, docs/operation.md, docs/quickstart.md, docs/references.md, docs/release-notes.md, docs/resource-groups-api.md, docs/routing-rules.md, docs/security.md
- Add logo on each page
- Use same layout in readme
- Use only three columns but add item lists
Please review @willmostly @vishalya @Chaho12
=> Improve navigation for docs

gateway-ha/pom.xml
Related to #184 
I also verified that the dependencies are still in the jar with dependencies as expected.
=> Use runtime scope for JDBC drivers

gateway-ha/pom.xml, pom.xml
The dependency moved in terms of groupid to `org.wiremock` and we have a duplicate declaration for that already.
Weirdly the package of the java classes did NOT move so there is no code to update.
=> Upgrade and fix wiremock dependency

gateway-ha/pom.xml
`1.4.14` is what dropwizard v:stable is using, so we will just use this version
=> Make ch.qos.logback dependency declarative

docs/quickstart-config.yaml, gateway-ha/gateway-ha-config-docker.yml, gateway-ha/gateway-ha-config.yml
This is should be default value, dropwizard changed the defaults from 1.0 to some higher version. It takes care of the issues like https://github.com/trinodb/trino-gateway/issues/114
=> Set the defaults to forward the headers

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java
Refactor to make the rewriting logic more explicit. This does not introduce any logical changes, but explicitly separates sticky routing from routing group based routing in preparation for the introduction of new sticky routing strategies such as https://github.com/trinodb/trino-gateway/pull/188.
=> Refactor rewriteTarget

gateway-ha/pom.xml, pom.xml
Follows dependency declaration style in Trino project.
=> Inline dependency version

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStats.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
Same as https://github.com/trinodb/trino-gateway/pull/241
=> Remove unused field

docker/gateway-compose.yml, docker/postgres-backend-compose.yml
The expected restart policy should be decided by users, not us. 
Restarting these containers automatically looks annoying for me.
=> Remove restart policy from docker compose file

gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackend.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackendDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaRoutingManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java
=> Use JDBI for gateway_backend

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/JdbcConnectionManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsGlobalProperties.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsGlobalPropertiesDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
=> Use JDBI for resource_groups_global_properties

docs/release-notes.md
Assemble the release notes for Trino Gateway 6 release.
- #181 ✅ rn ✅ docs
- #182 ✅ rn ✅ docs
- #180 ✅ rn ✅ docs
- #185 ✅ rn ✅ docs
- #189 ✅ rn ✅ docs
- #193 ✅ rn ✅ docs
- #183 ✅ rn ✅ docs
- #190 ✅ rn ✅ docs
- #191 ✅ rn ✅ docs
- #192 ✅ rn ✅ docs
- #113 ✅ rn ✅ docs
- #198 ✅ rn ✅ docs
- #178 ✅ rn ✅ docs
- #199 ✅ rn ✅ docs
- #201 ✅ rn ✅ docs
- #200 ✅ rn ✅ docs
- #203 ✅ rn ✅ docs
- #204 ✅ rn ✅ docs
- #205 ✅ rn ✅ docs
- #206 ✅ rn ✅ docs
- #207 ✅ rn ✅ docs
- #208 …
=> Add release notes for Trino Gateway 6

pom.xml
This is fine since we rely on CI runs before release build as evidence.
As requested by @martint 
Can you maybe confirm @wendigo - the idea is that the mvn release prepare run should not run tests again so its faster. I just lifted this approach from the trino root pom
=> Avoid test run in release build

gateway-ha/src/test/java/io/trino/gateway/CustomTrinoImageNameSubstitutor.java, gateway-ha/src/test/resources/testcontainers.properties
Problem: Some tests download trino docker images from public dockerhub. For example: https://github.com/trinodb/trino-gateway/blob/e2aaa0e9c71ae69767f842a3f4834f9d531d6620/gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java#L55
However, this will fail when running behind a proxy. Our in-house images have different names from the names on dockerhub.  Therefore, we need a way to override `trinodb/trino` to a completely different name when necessary. This will eventually expand to other public images as they are added to the codebase.
=> allow customization of test containers image name

docs/release-notes.md
trivial. found a typo for a broken link while reviewing release notes
=> Fix typo in issue link at release note

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java
The logic for extracting a query id from the request query was broken. The test for this functionality was also broken, since it passed the `query` to the extraction method as part of the `path`.
=> Fix query id extraction from request query

docs/quickstart-config.yaml, gateway-ha/gateway-ha-config-docker.yml, gateway-ha/gateway-ha-config.yml, gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsInfoApiMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ServerInfo.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/ClusterStatsMonitorType.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/ClusterStatsMonitorModule.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
This adds a lightweight health check against the coordinator's `v1/info`. A cluster is set to healthy as long as the coordinator returns a 200 response and is not in the process of starting. `v1/info` does not require authentication, which  addresses the concerns raised in
* https://github.com/trinodb/trino-gateway/issues/233
* https://github.com/trinodb/trino-gateway/issues/166
* https://github.com/trinodb/trino-gateway/issues/66
=> Get cluster health from v1/info

gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java
Agreed the removal on https://trinodb.slack.com/archives/C059KUNPTSP/p1709810596964029
=> Remove unused code

gateway-ha/pom.xml
Remove duplicate config and some cleanup (probability comes from merge conflicts).
https://github.com/trinodb/trino-gateway/blob/bad988ea255c6e0185c27fdbb487e67bfc558e2c/gateway-ha/pom.xml#L531-L557
=> Cleanup pom.xml

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ExactMatchSourceSelectors.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ExactMatchSourceSelectorsDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java
Relates to https://github.com/trinodb/trino-gateway/issues/229
=> Use JDBI for ExactMatchSourceSelectors

docs/quickstart-config.yaml
Update logging in quickstart-config.yaml.
`logging: type: external` is required after #260. Otherwise the following error will occur.
```
$ java -Xmx1g --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED \
-Dlog.levels-file=gateway-ha/etc/log.properties \
-jar gateway-ha/target/gateway-ha-7-SNAPSHOT-jar-with-dependencies.jar \
server docs/quickstart-config.yaml
2024-03-21T17:50:24.270+0900    INFO    main    io.airlift.log.Logging  Logging to stderr
2024-03-21T17:50:24.306+0900    INFO    main    stderr  SLF4J(W): Class path contains multiple SLF4J providers.
2024-03-21T17:50:24.306+0900    INFO    main    stderr  SLF4J(W): Found provider [org.slf4j.jul.JULServiceProvider@4de5031f]
2024-03-21T17:50:24.307+0900    INFO    main    stderr  SLF4J(W): Found …
```
=> Update logging in quickstart-config.yaml

docs/installation.md, docs/release-notes.md
Assemble the release notes for Trino Gateway 7 release.
- #257 ✅ rn ✅ docs
- #262 ✅ rn ✅ docs
- #258 ✅ rn ✅ docs
- #261 ✅ rn ✅ docs
- #246 ✅ rn ✅ docs
- #266 ✅ rn ✅ docs
- #267 ✅ rn ✅ docs
- #274 ✅ rn ✅ docs
- #271 ✅ rn ✅ docs
- #275 ✅ rn ✅ docs
- #116 ✅ rn ✅ docs
- #272 ✅ rn ✅ docs
- #273 ✅ rn ✅ docs
- #265 ✅ rn ✅ docs
- #264 ✅ rn ✅ docs
- #256 ✅ rn ✅ docs
- #260 ✅ rn ✅ docs
- …
=> Add release notes for Trino Gateway 7

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java
Related to #41.
Remove `io.dropwizard.metrics` and `io.dropwizard:dropwizard-servlets`.
Subclass of `HealthCheck` or `Task` in classpath with `io.trino.*` prefix were injected automatically.
This PR remove this auto injection function.
**Please let me know if anyone is using this feature.**
Verified there are no subclass of `HealthCheck` nor `Task` in the current code base.
`http://localhost:9082/healthcheck` and `http://localhost:9082/tasks` work as before.
`op=register type=healthcheck` and `op=register type=task` are not being called when using quickstart-config.yaml.
```
2024-03-25T23:03:56.201+0900	INFO	main	io.trino.gateway.baseapp.BaseApp	op=create auto_scan_packages=io.trino
2024-03-25T23:03:57.258+0900	INFO	main	io.dropwizard.core.server.DefaultServerFactory	Registering jersey …
```
=> Remove io.dropwizard.metrics and dropwizard-servlets

gateway-ha/pom.xml, gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
Part of #41 
Replace WireMock with okhttp3:mockwebserver.
Trino is also using `okhttp3:mockwebserver` for testing.
WireMock depends on jetty 11 which is incompatible with Airlift (jetty 12 & EE 10).
Update okhttp3 to the latest version (`3.14.9` -> `4.12.0`).
Side effect:
New version of okhttp3 won't send Authorization header after a redirect. (See: https://github.com/trinodb/trino/issues/21026)
This will break credentials-based authentication if anyone is using:
`Trino-gateway -> (some proxy with redirect mode) -> Trino`.
Needs to override this behavior and always send Authorization header.
=> Replace WireMock with okhttp3:mockwebserver

gateway-ha/pom.xml, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
Part of #41. Follow up of #291.
We are using okhttp for form authentication and some tests only.
The issue of new version okhttp3 won't send Authorization header after a redirect doesn't matter.
=> Update OkHttp to 4.12.0

gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java
Fix the error caused by the missing 'audiences' configuration
```
ERROR	pool-6-thread-8 - POST /webapp/getDistribution	io.trino.gateway.ha.security.LbOAuthManager	Could not validate token or get claims from it.
```
See details at: https://trinodb.slack.com/archives/CG9K9MX1V/p1711980180964969
=> Fix the error caused by the missing 'audiences' configuration

docker/README.md, docker/docker-compose.yml
~It seems unncessary as of now to have healthcheck confs in both minimal compose and each extended compose files.~
~IDE shows `Missing required key(s): 'test'` error too so unless a different health check is needed for running minimal compose, it seems better to get rid of one conf (makes it more confusing)~
- ~[gateway-compose yaml](https://github.com/trinodb/trino-gateway/blob/main/docker/gateway-compose.yml) and [postgres compose yaml](https://github.com/trinodb/trino-gateway/blob/main/docker/postgres-backend-compose.yml)~
Since docker compose files is merged into one + docker compose conf is updated,
This PR 
- adds a test as IDE shows `Missing required key(s): 'test' warning
- suggests users to change in health check depending on the workload in production usage
=> Suggest changing health check conf in docker compose

gateway-ha/pom.xml, pom.xml
Update Jdbi to 3.45.1 to sync with Trino.
https://github.com/trinodb/trino/blob/5f5210f039bb4c8055a6267805b11063dbb2c6d3/pom.xml#L279-L285
=> Update Jdbi to 3.45.1

gateway-ha/pom.xml
Currently the `pnpm-lock.yaml` has the version locked in at `registry.npmmirror.com`. Building it behind a company proxy will likely fail if your company doesn't allow to download from external sources. Therefore, we can specify the `pnpmRegistryURL` for it.  Specifying this parameter will get rid of the hard-coded path and only use the version part of the dependency.
This can help align the versions but use different download URLs simultaneously
For example: 
Was:
```
'@douyinfe/semi-icons':
specifier: ^2.47.1
version: registry.npmmirror.com/@douyinfe/semi-icons@2.47.1(react@18.2.0)
```
Now:
```
'@douyinfe/semi-icons':
specifier: ^2.47.1
version: 2.47.1(react@18.2.0)
```
(X) Release notes are required. …
=> Allow pnpmRegistryURL to be configurable

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java
Part of #41.
Remove org.reflections.
Use static resource binding instead of runtime reflection based binding.
This is a common practice in Trino (eg. [CoordinatorModule.java](https://github.com/trinodb/trino/blob/fbaff0224df8b1448ba095e9da9139761b2c0f0a/core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java#L194))
Also makes [conditioinal binding based on a config using Airlift](https://github.com/airlift/airlift/blob/master/docs/recipes.md#how-do-i-do-conditional-binding-based-on-a-config-value) easier in the future.
Before PR:
```
2024-04-08T13:40:40.043+0900	INFO	main	io.trino.gateway.baseapp.BaseApp	op=register_start configuration=Configuration{server=DefaultServerFactory{applicationConnectors=[io.dropwizard.jetty.HttpConnectorFactory@37a1beb3], …
```
=> Use static resource binding instead of runtime reflection based binding

webapp/pnpm-lock.yaml
Get rid of the hardcoded dependency path in `pnpm-lock.yaml` to allow download from other URLs. This is a follow-up of https://github.com/trinodb/trino-gateway/pull/303
```markdown
* 
```
=> Fix pnpm-lock.yaml having hardcoded dependency path in version

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/config/LdapConfiguration.java
Part of #41.
Remove dropwizard configuration and jackson.
Dropwizard configuration support override values using system properties.
For example, `-Dlb.ldapHost=test.com` can override the ldapHost value in `SomeLdapConfig.yml`.
Not sure is anyone relying on this feature.
=> Remove dropwizard configuration and jackson

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyHandlerStats.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java
Part of #41.
Abstract the stats counting using ProxyHandlerStats.
This is similar to the implementation inTrino, see: [CallStats.java](https://github.com/trinodb/trino/blob/master/lib/trino-hdfs/src/main/java/io/trino/hdfs/CallStats.java)
Add airlift stats in parallel with io.dropwizard.metrics.
Can't remove io.dropwizard.metrics right now because we can't export airlift stats in REST API under Dropwizard.
After switch to Airlift, `ProxyHandlerStats` and `CounterStat` will stay.
`com.codahale.metrics.Meter` and `Environment` will be gone.
|                            | JMX                               | JMX using RESTful API                      | JMX Provider                     |
|----------------------------|-----------------------------------|------------------------------------------ …
=> Add airlift stats

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/LoginResource.java
Fixes the restUserInfo function to return Trino Gateway Roles (ADMIN, USER, API) to the Webapp, which is what the webapp expects.
I opened [this PR to map LDAP groups to Trino gateway roles](https://github.com/trinodb/trino-gateway/pull/292) and then came up with this simpler solution.
The following configs will break in the current (prior to this commit) version of Trino gateway because the admin user will not have admin privileges within the webapp like it should. This is because the webapp checks role membership by comparing the roles passed to those in an enum.
breaking auth example:
```
authorization:
admin: .*FOO.*
user: .*BAR.*
api: .*BAZ.*
presetUsers:
admin1:
password: password
privileges: FOO_BAR
user1:
password: password
privileges: BAR_BAZ
```
This broken example works as …
=> Fix rest user info to match API auth with Webapp Auth

gateway-ha/pom.xml
Part of #41 
Update JWKS RSA to 0.22.1.
Resolve the following error when updating to Airlift.
This error happens when we drop dropwizard-dependencies.
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.4.1:enforce (default) on project gateway-ha: 
[ERROR] Rule 2: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps failed with message:
[ERROR] Failed while enforcing RequireUpperBoundDeps. The error(s) are [
[ERROR] Require upper bound dependencies error for commons-codec:commons-codec:1.13 paths to dependency are:
[ERROR] +-io.trino.gateway:gateway-ha:8-SNAPSHOT
[ERROR]   +-com.auth0:jwks-rsa:0.9.0
[ERROR]     +-commons-codec:commons-codec:1.13
[ERROR] and
[ERROR] +-io.trino.gateway:gateway-ha:8-SNAPSHOT
[ERROR] …
```
=> Update JWKS RSA to 0.22.1

docs/installation.md
- with process forwarding config only for now
OAuth2 and other tips will follow in separate PRs from @willmostly and others.
Replaces #217 
=> Add Trino configuration docs

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ServerInfo.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/ProxyBackendConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/Result.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/TableData.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/GlobalPropertyRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QueryDistributionRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QueryGlobalPropertyRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QueryHistoryRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QueryResourceGroupsRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QuerySelectorsRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/ResourceGroupsRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/RestLoginRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/SelectorsRequest.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/response/BackendResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/response/DistributionResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/LoginResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ResourceGroupsManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyServerConfiguration.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestObjectSerializable.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java
Part of #41 
Annotate JsonProperty on getter instead of field. This ensure objects are serializable without enable Jackson AUTO_DETECT_GETTERS feature. AUTO_DETECT_GETTERS is disabled by Airlift. This PR ensure the objects are serializable after switch to Airlift.
Without this change, we'll get a JsonMappingException error when AUTO_DETECT_GETTERS is disabled.
```
com.fasterxml.jackson.databind.JsonMappingException: class com.fasterxml.jackson.databind.ser.BeanPropertyWriter cannot access a member of class io.trino.gateway.ha.domain.response.BackendResponse with modifiers "private" (through reference chain: io.trino.gateway.ha.domain.response.BackendResponse["queued"])
```
All Request objects are converted to record to reduce boilerplate.
(x) This is not user-visible or is docs only, and …
=> Annotate JsonProperty on getter

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestAuthorization.java, gateway-ha/src/test/resources/auth/auth-test-config.yml
Add test for authorization.
This is a regression test for #310.
=> Add test for authorization

docs/assets/gateway-routing-flow.svg, docs/design.md, docs/development.md, docs/gateway-api.md, docs/installation.md, docs/operation.md, docs/quickstart.md, docs/references.md, docs/release-notes.md, docs/resource-groups-api.md, docs/routing-logic.md, docs/routing-rules.md, docs/security.md, gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/config/GatewayCookieConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/GatewayCookieConfigurationPropertiesProvider.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/OAuth2GatewayCookieConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/OAuth2GatewayCookieConfigurationPropertiesProvider.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/GatewayCookie.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/OAuth2GatewayCookie.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyServletImpl.java, gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/resources/test-config-template.yml
This adds an additional routing strategy for the Gateway. Currently the Gateway checks all incoming requests for a query ID. If one is found, the cluster running that query is looked up and the query is routed to that cluster. All other requests are sent to a semi random backend cluster in the routing group chosen by the `RoutingGroupSelector` based on the information present in the request. These routing strategies are not sufficient to solve issues such as https://github.com/trinodb/trino-gateway/issues/165. For https://github.com/trinodb/trino-gateway/issues/165, the Gateway needs the capability to route a request to the same backend that a previous request was sent to.
This adds the ability to add a session cookie, and to map that session cookie to a specific backend. This is lower …
=> Add cookie based routing for selected paths

docs/release-notes.md
This change stops relying on the automated github rendering of the markdown file and the links to the pull requests and issues. It explicitly adds the link like done in newer releases.
Necessary for clean rendering of the release notes in the site - see #254 
=> Add explicit link titles

gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryCountBasedRouter.java
The new QueryCountBasedRouter router fails to route any request due to uninitialized userQueryCount map attribute.
My guess is that the refactoring for Record to store the cluster stats removed the initialization.
This PR fixes the initialization of the userQueryCount map in the QueryCountBasedRouter. 
Also, modified the tests to take care of the scenario.
This is a bug fix
() Release notes are required. Please propose a release note for me.
() Release notes are required, with the following suggested text:
```markdown
* 
```
=> Initialize the null userQueueCount map

docs/installation.md, helm/trino-gateway/.helmignore, helm/trino-gateway/Chart.yaml, helm/trino-gateway/templates/NOTES.txt, helm/trino-gateway/templates/_helpers.tpl, helm/trino-gateway/templates/deployment.yaml, helm/trino-gateway/templates/hpa.yaml, helm/trino-gateway/templates/ingress.yaml, helm/trino-gateway/templates/secrets.yaml, helm/trino-gateway/templates/service.yaml, helm/trino-gateway/templates/serviceaccount.yaml, helm/trino-gateway/templates/tests/test-connection.yaml, helm/trino-gateway/values.yaml
Add a Helm chart. This chart passes configuration directly from the values.yaml to the gateway config.yaml, loosely coupling the chart structure with the configuration of the gateway itself. Secrets for configurations that contain sensitive data are also supported.
This chart is only compatible with version 7 of the Trino Gateway docker image. Before this chart is released, we should release a public image with https://github.com/trinodb/trino-gateway/pull/318. This chart can then be updated to remove the version number from the executable path, making it compatible with all versions of the docker image going forward.
(X ) Release notes are …
=> Add Helm chart for k8s deployment

docs/release-notes.md
Assemble the release notes for Trino Gateway 8 release.
- #225 ✅ rn ✅ docs
- #290 ✅ rn ✅ docs
- #291 ✅ rn ✅ docs
- #293 ✅ rn ✅ docs
- #295 ✅ rn ✅ docs
- #98 ✅ rn ✅ docs
- #247 ✅ rn ✅ docs
- #238 ✅ rn ✅ docs
- #284 ✅ rn ✅ docs
- #287 ✅ rn ✅ docs
- #299 ✅ rn ✅ docs
- #301 ✅ rn ✅ docs
- #296 ✅ rn ✅ docs
- #303 ✅ rn ✅ docs
- #306 ✅ rn ✅ docs
- #304 ✅ rn ✅ docs
- #307 ✅ rn ✅ docs
- …
=> Add release notes for Trino Gateway 8

gateway-ha/pom.xml
- Change the webapp outputDirectory to `${project.build.outputDirectory}/static`
- Move copy static step to `prepare-package` phase
```markdown
* 
```
=> Ensure inclusion of UI in JAR and container artifacts

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/PublicResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/BackendStateManager.java
BackendState record is a map of two fields that is used to return the `queuedQueryCount` and `runningQueryCount`. We have these information in `ClusterStats` class so we can simply use that.
=> Remove BackendState record

helm/trino-gateway/templates/deployment.yaml
This fixes a nil pointer issue when Helm evaluates the deployment template before the secrets template creates `trino-gateway-configuration`. It also fixes an issue with the liveness and readiness probe templates.
The nil pointer issue may result in an error message like
```
Error: template: trino-gateway/templates/deployment.yaml:20:71: executing "trino-gateway/templates/deployment.yaml" at <"trino-gateway-configuration">: nil pointer evaluating interface {}.resourceVersion
```
The templating issue results in a `livenessProbe` like:
```
livenessProbe:
httpGet:
path: /
port: 9082
initialDelaySeconds: .Values.livenessProbe.initialDelaySeconds
periodSeconds: .Values.livenessProbe.periodSeconds
failureThreshold: .Values.livenessProbe.failureThreshold
timeoutSeconds: …
```
=> Fix install and probe bugs

gateway-ha/pom.xml
This fixes the following warning:
```
Warning:  The artifact mysql:mysql-connector-java:jar:8.0.33 has been relocated to com.mysql:mysql-connector-j:jar:8.0.33: MySQL Connector/J artifacts moved to reverse-DNS compliant Maven 2+ coordinates.
```
=> Use com.mysql:mysql-connector-j

docs/installation.md
- For process forwarded flag
- Related to using HTTPS terminating load balancer
* https://github.com/trinodb/trino/pull/22166
=> Add link to Trino docs

gateway-ha/src/main/java/io/trino/gateway/ha/security/OidcCookie.java
OidcCookie should be using `SameSite=LAX` instead of `SameSite=STRICT`.
A redirect from OAuth provider to gateway will cause the cookie being blocked when `SameSite=STRICT`.
(See https://stackoverflow.com/a/42220786)
The tests missed this issue because Dropwizard ignored the SameSite setting and didn't set it at all (looks like a bug). I discovered this issue when I was testing it on Airlift.
https://github.com/trinodb/trino-gateway/blob/5d7e30c2fd94ac3279cd77dec5724f9904f5690a/gateway-ha/src/main/java/io/trino/gateway/ha/security/OidcCookie.java#L45
`SameSite` is missing:
```
$ curl -vvvv -k -XPOST https://localhost:9080/sso
...
< HTTP/1.1 200 OK
< Date: Thu, 30 May 2024 05:34:14 GMT
< Strict-Transport-Security: max-age=2000; includeSubDomains
< Date: Thu, 30 May 2024 05:34:14 GMT
< …
```
=> Set SameSite to LAX for OidcCookie

docs/installation.md, gateway-ha/etc/config.properties, gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java
Support reading log properties from file instead of command line using `-Dlog.<config>`.
- use [loadProperties](https://github.com/airlift/airlift/blob/master/configuration/src/main/java/io/airlift/configuration/ConfigurationLoader.java#L35-L47) instead of [getSystemProperties](https://github.com/airlift/airlift/blob/master/configuration/src/main/java/io/airlift/configuration/ConfigurationLoader.java#L68C39-L71)
```markdown
* Support reading log properties from file
```
=> support reading log properties from file

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java
Both `userName` and `source` in QueryHistory are nullable.
`userName` (ie. `X-Trino-User`) is optional in request. If not supplied, the session user is automatically determined via user mapping by coordinator. Trino-gateway won't be able to know the user determined by user mapping.
`source` is optional in Trino:
https://github.com/trinodb/trino/blob/edd5d5bec766e90053e7c28ff9c9dc254790fdb0/core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java#L45
=> Remove non-null restriction for QueryHistory

webapp/src/components/cluster.tsx
Fix #331 
UI render the cluster elements using the result from `/webapp/getAllBackends`.
The result from `/webapp/getAllBackends` doesn't guarantee the order of the clusters.
Sorting the clusters before rendering solves the issue.
```markdown
* Fix cluster reordering issue in the `/cluster` WebUI
```
=> Fix UI element reordering in the `/cluster` WebUI

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestResourceGroupsManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
Create resource group was broken after #287.
`resource_group_id` should be generated by database with AUTO_INCREMENT in DDL.
Tests didn't cover create multiple resource groups so we missed that.
(X) Release notes are required, with the following suggested text:
```markdown
* Fix create new resource group
```
=> Fix create new resource group

gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java, gateway-ha/src/test/resources/trino-config.properties
Fix #395 
Trino 451 reject `X-Forwarded-*` headers by default, which causes some tests to fail.
This PR adds `http-server.process-forwarded` to the Trino test container to make Trino accept X-Forwarded-* headers.
=> Add http-server.process-forwarded to Trino test container

docs/development.md
Adding @oneonestar is already approved and configured in github. Just making the info public here.
=> Add oneonestar as maintainer

docs/development.md
Remove docs for TLS 1.0 and 1.1.
TLS 1.0 and TLS 1.1 were deprecated since 2021.
Refs:
* https://datatracker.ietf.org/doc/html/rfc8996
* https://techcommunity.microsoft.com/t5/windows-it-pro-blog/tls-1-0-and-tls-1-1-soon-to-be-disabled-in-windows/ba-p/3887947
=> Remove docs for TLS 1.0 and 1.1

docs/security.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/OAuthConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbAuthenticator.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java
Close #322
Add support for using OIDC claim for authorization.
An OAuth claim can be used by setting the `privilegesField` in the OAuth configuration.
The privileges retrieved will be match with the `authorization` session.
Privileges field can be `List<String>` or `String`.
The following example extract privileges from the claim `roles` and match it in authorization.
Config:
```
authentication:
defaultType: "oauth"
oauth:
privilegesField: roles
authorization:
admin: (.*)ADMIN(.*)
user: (.*)USER(.*)
api: (.*)API(.*)
```
Example 1: ID token with a privileges field using the `List<String>` type:
```
{
"sub": "alice",
"roles": [
"ADMIN", "USER"
],
...
}
```
Example 2: ID token with a privileges field using the `String` type:
```
{
"sub": "alice",
"roles": "ADMIN_USER",
...
}
```
(x) Release …
=> Add support for using OIDC claim for authorization

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/RouteToBackendResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
- Add support for DELETE method on proxyserver
- Trino client REST API [use DELETE to nextUri terminates a running query](https://trino.io/docs/current/develop/client-protocol.html#http-methods)
=> Add proxy handler for DELETE method

docs/quickstart.md, docs/release-notes.md
Assemble the release notes for Trino Gateway 10 release.
Also adjust rest of docs to version 10
Requirement for #410 
- #341 ✅ rn ✅ docs
- #343 ✅ rn ✅ docs
- #350 ✅ rn ✅ docs
- #348 ✅ rn ✅ docs
- #356 ✅ rn ✅ docs
- #361 ✅ rn ✅ docs
- #345 ✅ rn ✅ docs
- #363 ✅ rn ✅ docs
- #364 ✅ rn ✅ docs
- #289 ✅ rn ✅ docs
- #367 ✅ rn ✅ docs
- #372 ✅ rn ✅ docs
- #329 ✅ rn ✅ docs
- #371 ✅ rn ✅ docs
- #374 ✅ rn ✅ docs
- #352 ✅ rn ✅ docs
- #340 ✅ rn ✅ docs
- #373 ✅ rn ✅ docs
- …
=> Add release notes for Trino Gateway 10

docs/quickstart.md
Trino 451 reject X-Forwarded-* headers by default, so following quickstart guide doesn't work properly.
This PR guides `JAVA_TOOL_OPTIONS` when running Trino image.
- I find this much simpler than creating and mouting config.properties file 
https://github.com/trinodb/trino-gateway/pull/396
```markdown
* 
```
=> Add http-server.process-forwarded to Trino in quickstart doc

docs/security.md, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsInfoApiMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ForMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/ClusterStatsMonitorModule.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
Make ClusterStatsMonitor http client options can configurable.
#434 
```markdown
* 
```
=> Make ClusterStatsMonitor http client options can configurable

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistoryDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManager.java
Resolves the following error when using Spanner by Explicitly Cast text values in [CONCAT function](https://cloud.google.com/spanner/docs/reference/postgresql/functions-and-operators#string_functions). 
`SELECT CONCAT(FLOOR(created / 1000 / 60)::text) AS minute,`
<details><summary>Resolved the following error</summary>
```
trino-gateway org.jdbi.v3.core.statement.UnableToExecuteStatementException: org.postgresql.util.PSQLException: ERROR: Postgres function concat(double precision) is not supported - Statement: 'SELECT CONCAT(FLOOR(created / 1000 / 60)) AS minute,
trino-gateway        backend_url AS backend_url,
trino-gateway        COUNT(1) AS query_count
trino-gateway FROM query_history
trino-gateway WHERE created > $1
trino-gateway GROUP BY minute, backend_url
trino-gateway ' …
```
=> Remove unnecessary CONCAT function

docs/operation.md, gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java
Add JmxOpenMetricsModule.
```markdown
* Add openmetrics endpoint at `/metrics`
```
=> Add JmxOpenMetricsModule

gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoRequestUser.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueryProperties.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoRequestUser.java
Add serialization for TrinoQueryProperties and TrinoRequestUser so that they can be used in the REST resource group selector.
=> Add serialization for TrinoQueryProperties and TrinoRequestUser

helm/trino-gateway/Chart.yaml
Update Helm chart version to 10.
Related to #437.
`version` should follow semantic versioning (X.Y.Z).
I'm thinking about:
```
X follows trino-gateway release
Y for helm chart breaking updates
Z for minor bug fixes
```
wdyt @willmostly 
=> Update Helm chart version to 10

docs/installation.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/RoutingConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestNoXForwarded.java, gateway-ha/src/test/resources/test-config-without-x-forwarded-template.yml
In some cases it can be useful to have a Trino backend communicate directly with the client once it has been selected by the Trino Gateway's routing logic. This can be accomplished by not setting the `X-Forwarded` headers.
(x ) Release notes are required, with the following suggested text:
Optionally disable adding X-Forwarded-* headers to the request
=> Add option to not add X-Forwarded headers

.github/workflows/ci.yml
Attempting to run build with 21 and 22 like in Trino to enable some safety and move to 22 next. 
required for https://github.com/trinodb/trino-gateway/pull/441 in my opinion
=> Run build with Java 21 and 22

.mvn/wrapper/maven-wrapper.properties
Just a maintenance task... users might need to update mvnd if they use that.. but we dont document or talk about that anyway
=> Use Maven 3.9.9 for build

.github/workflows/ci.yml
Just a mainteance task .. hoping to get rid of the node20 warning 
```
The following actions use a deprecated Node.js version and will be forced to run on node20: actions/checkout@v3, docker/setup-qemu-action@v2, azure/setup-helm@v3, actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```
Follow up - seems to work. No more warnings at https://github.com/trinodb/trino-gateway/actions/runs/10497055629 for example
=> Update github actions versions

gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java
Set X-Forwarded-Host when client using HTTP/2.
Fix #451 
OkHttp convert `Host` header into HTTP/2 `:authority` header, thus the test is valid.
Ref:
https://github.com/square/okhttp/blob/28075d78310e895b4673cd5433a69b80d42433c2/okhttp/src/main/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt#L139-L143
https://github.com/square/okhttp/blob/28075d78310e895b4673cd5433a69b80d42433c2/okhttp/src/main/kotlin/okhttp3/internal/http2/Http2ExchangeCodec.kt#L172-L175
```markdown
* Fix X-Forwarded-Host not being set when client using HTTP/2
```
=> Set X-Forwarded-Host when client using HTTP/2

helm/trino-gateway/templates/_helpers.tpl, helm/trino-gateway/values.yaml
This PR adds commonLabels to all resources. For some kubernetes instances, it is required to have custom labels.
```markdown
Add commonLabels to helm chart 
```
=> Add commonLabels to helm chart

docs/docs.md
As discussed in dev sync and https://github.com/trinodb/trino-gateway/pull/460
=> Add docker command for docs build

gateway-ha/src/main/java/io/trino/gateway/ha/router/GatewayCookie.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/OAuth2GatewayCookie.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
The cookie used for maintaining stickiness during an OAuth2 handshake forwards requests to a path in the `deleteCookiePath` list such as `/logout` to a random backend. The requests should be forwarded to the same backend to allow any server side sessions to be cleaned up. 
(x ) Release notes are required, with the following suggested text:
```markdown
* Ensure OAuth logout requests are forwarded to the Trino cluster that initiated the handshake.
```
=> Correct OAuth cookie logout behavior

docs/routing-rules.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/RoutingRulesConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/RulesExternalConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/RulesType.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RuleReloadingRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingGroupExternalBody.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingGroupExternalResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java
Add ~RESTful API method of~ external selecting routing group
Allows user to set a RESTful API endpoint that would return routing group.
https://trinodb.slack.com/archives/C059KUNPTSP/p1720619490704499
(x) Release notes are required. Please propose a release note for me.
```markdown
* Added external routing group selector. Users can now set a RESTful API endpoint that returns a routing group to be routed.
```
=> Add external routing group selector

docs/operation.md, docs/quickstart.md, docs/release-notes.md, docs/security.md, helm/trino-gateway/Chart.yaml
Assemble the release notes for Trino Gateway 11 release.
Also adjust rest of docs to version 11
Requirement for #459
* #421 ✅ rn ✅ docs
* #426 ✅ rn ✅ docs
* #430 ✅ rn ✅ docs
* #436 ✅ rn ✅ docs
* #375 ✅ rn ✅ docs
* #429 ✅ rn ✅ docs
* #431 ✅ rn ✅ docs
* #438 ✅ rn ✅ docs
* #417 ✅ rn ✅ docs
* #443 ✅ rn ✅ docs
* #445 ✅ rn ✅ docs
* #444 ✅ rn ✅ docs
* #442 ✅ rn ✅ docs
* #457 ✅ rn ✅ docs 
* #456 ✅ rn ✅ docs
* …
=> Add release notes for Trino Gateway 11 and related changes

docs/routing-rules.md
Fixes #468
Objectmapper expects the boolean fields without the `is` prefix. Hence, instead of `isAnalyzeRequest`, `analyzeRequest` should be used for configuration.
=> Fixed analyze request

gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RouterException.java
Adhoc routing group is the fallback routing group if no routing group is provided. If there are no clusters available for this group, we should log and throw an error
=> Throw exception when no clusters are found for adhoc routing group

gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/resources/rules/routing_rules_trino_query_properties.yml
Fix https://github.com/trinodb/trino-gateway/issues/478
```markdown
* 
```
=> Fix IndexOutOfBoundsException caused by switch-case statements with no breaks

gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/resources/test-config-template.yml
Add destination cluster a query is routed to in the cookie. More details here of the use-case here: https://github.com/trinodb/trino-gateway/issues/465
Fixes https://github.com/trinodb/trino-gateway/issues/465
```markdown
* The cookie data for requests to `/v1/statement` API would include the cluster to which a query got routed named as `trinoClusterHost`.
```
=> Add destination cluster info to response cookie

gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java
`List<Protocol>`  provides a nicer readability on IDE. 
Before this change:
After this change:
=> Minor cleanup in TestGatewayHaSingleBackend

docs/installation.md, gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java, gateway-ha/src/main/java/io/trino/gateway/ha/util/ConfigurationUtils.java, gateway-ha/src/test/java/io/trino/gateway/ha/util/TestConfigurationUtils.java
Allow setting config values from env variables.
This is the same syntax used by Trino: https://trino.io/docs/current/security/secrets.html
```markdown
* Allow setting config values from environment variables
```
=> Allow setting config values from env variables

docs/routing-rules.md
When decoding JSON response using `io.airlift.http.client#createJsonResponseHandler` at [external routing group selector code](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java#L98), 
JSON response could be compressed in GZIP (or whatever format) depending on the network configuration.
This is not expecected behaviour by Airlift as it read bytes.
- https://github.com/airlift/airlift/blob/master/http-client/src/main/java/io/airlift/http/client/JsonResponseHandler.java#L68-L91
So, I suggest adding `'Accept-Encoding'` to docs so that user can know they might need to exclude it when making API request to server. 
( ) Release …
=> Update docs to add encoding header to be excluded

gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoRequestUser.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFilter.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaWithRoutingRulesSingleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestNoXForwarded.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestAuthorization.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbFilter.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbLdapClient.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java, pom.xml
=> Update errorprone rules and fix some warning

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/LbOAuthManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java, pom.xml
=> Enable some errorprone rules and remove redundant mock usage

.github/pull_request_template.md
Copy from https://github.com/trinodb/trino/pull/23636 with the following changes:
* Remove the change on checkbox (Looks like the checkbox still being converted into a tasklist)
* Update links
```diff
-at https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md 
-and contact us on #core-dev in Slack. -->
+at https://trinodb.github.io/trino-gateway/development/#contributing
+and contact us on #trino-gateway-dev in Slack. -->
```
- ( ) Release notes are required. Please propose a release note for me.
- ( ) Release notes are required, with the following suggested text:
```markdown
```
=> Improve pull request description template

gateway-ha/pom.xml, pom.xml
=> Remove redundant `dep.trino.version` declaration and inline `dep.mysqlconnector.version`

mkdocs.yml
https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#configuration
Before this change:
After this change:
=> Enable syntax highlight in documentation

.github/pull_request_template.md
No reason to use a different style from Trino. 
=> Remove leading `-` from PR template

docs/release-notes.md
`https://trinodb.github.io/trino-gateway/release-notes/#trino-gateway-11-12-sep-2024`
will be
`https://trinodb.github.io/trino-gateway/release-notes/#11`
=> Shorten release note permalink

docs/routing-rules.md, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueryProperties.java
Add a field (private Optional<String> ParseErrorMessage) to TrinoQueryProperties class that stores `e.getMessage()` when there is error.
https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java#L213-L224
We have server connected with gateway that runs explain before actually running the query.
But not all queries need to be sent with explain.
For example there are cases where queries with parsing failure (no need to run explain cause it is highly likely to fail anyway due to syntax error)
- we need to tell user on WHY query has failed, but running another sql parser or explain is waste of resource
- since gateway already does query parsing, why not use that failure info.
(x) This is not user-visible or is docs only, …
=> Add parsing error message field to TrinoQueryProperties

docs/installation.md, helm/trino-gateway/templates/deployment.yaml, helm/trino-gateway/values.yaml
Make the startup command configurable
This allows users to set java options such as `-Djavax.net.ssl.truststore=/path/to/truststore`, run short scripts, and otherwise customize startup. 
- ( ) This is not user-visible or is docs only, and no release notes are 
required.
- ( ) Release notes are required. Please propose a release note for me.
- ( x) Release notes are required, with the following suggested text:
Make the startup command configurable
=> Make startup command configurable

docs/docker.md, docs/installation.md, mkdocs.yml
This is a simple lift and shift with minor adjustments only for me. Ultimately we need to break up the installation section much better.
Details about follow up work in https://github.com/trinodb/trino-gateway/issues/519
=> Move docker readme to docs

gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoRequestUser.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoRequestUser.java
- Let's try to use the newly added TrinoRequestUser to extract the user from the query
- Fix the issue with TrinoRequestUser, the user is not extracted correctly as the whole header is parsed instead of the token
- (X) This is not user-visible or is docs only, and no release notes are required.
- ( ) Release notes are required. Please propose a release note for me.
- ( ) Release notes are required, with the following suggested text:
=> Use TrinoRequestUser to get the user for the query

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/HttpUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/RouteToBackendResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/config/TestHaGatewayConfiguration.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoRequestUser.java
Supersedes #504
Fixes https://github.com/trinodb/trino-gateway/issues/480
=> Rename QueryIdCachingProxyHandler to HttpUtils

gateway-ha/src/main/java/io/trino/gateway/ha/config/RequestAnalyzerConfig.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RuleReloadingRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueryProperties.java
Trino Gateway attempts to extract the query id from the body of queries using the [runtime.kill_query](https://trino.io/docs/current/connector/system.html#system-connector-procedures) procedure from the system catalog. This adds a test for this functionality.
=> Extract query ID from all kill_query procedure variations

docs/quickstart.md, docs/release-notes.md, helm/trino-gateway/Chart.yaml
Assemble the release notes for Trino Gateway 12 release and adjust rest of docs to version 12
* #463 ✅ rn ✅ docs
* #469 ✅ rn ✅ docs
* #471 ✅ rn ✅ docs
* #474 ✅ rn ✅ docs
* #470 ✅ rn ✅ docs
* #477 ✅ rn ✅ docs
* #479 ✅ rn ✅ docs
* #466 ✅ rn ✅ docs
* #488 ✅ rn ✅ docs
* #481 ✅ rn ✅ docs
* #494 ✅ rn ✅ docs
* #496 ✅ rn ✅ docs
* #492 ✅ rn ✅ docs
* #495 ✅ rn ✅ docs
* #493 ✅ rn ✅ docs
* #483 ✅ rn ✅ docs
* #489 ✅ …
=> Add release notes for Trino Gateway 12 and related changes 

webapp/src/components/layout.tsx
Removed GitHub button in UI as a link to the src code.
A link to the src code within an application feels unnecessary, also the website also has a link to the src code already.
More info at https://trino.io/development/process#release-note -->
```markdown
* Remove GitHub button from header in UI
```
=> Remove GitHub button in UI

gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/RouteToBackendResource.java, gateway-ha/src/test/java/io/trino/gateway/proxyserver/TestProxyRequestHandler.java
add handler for PUT request, which will be used in some trino distributions such as [SEP](https://www.starburst.io/platform/starburst-enterprise/). For instance, a PUT request is made to `ui/api/insights/openWorksheets` to save worksheets
=> add proxy handler for PUT request

webapp/src/api/base.ts
Fix #330.
Writing TypeScript for the first time. All I can say is this works on my local environment...
```markdown
* Implement automatic logout for Web UI
```
=> Implement automatic logout for WebUI

docs/quickstart.md, docs/release-notes.md
Assemble the release notes for Trino Gateway 13 release and adjust rest of docs to version 13.
As a follow up we need to merge https://github.com/trinodb/charts/pull/270 for the Helm chart after this release is done.
* #547 ✅ rn ✅ docs
* #550 ✅ rn ✅ docs
* #549 ✅ rn ✅ docs
* #551 ✅ rn ✅ docs
* #543 ✅ rn ✅ docs
* #544 ✅ rn ✅ docs
* #536 ✅ rn ✅ docs
* #558 ✅ rn ✅ docs
* #561 ✅ rn ✅ docs
=> Add Trino Gateway 13 release notes

docs/development.md, docs/index.md, docs/resources.md, docs/users.md, mkdocs.yml
Small for now but a good start in prep for Trino Summit. I will add more and more info for a bit and then merge and get it live after approval. And then we can add more after as well.
=> Add users page and improve contact info

docs/installation.md
Fix the wording in Health Checks section to avoid confusion
https://trinodb.slack.com/archives/C059KUNPTSP/p1733245765766909
```markdown
```
=> Fix Health Checks section in installation readme

.gitignore
The docker build creates that file and we should ignore it so accidental commit of it can be avoided.
na
=> Ignore version output file for git

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java
This fixes build failures with some newer OS versions, but avoids any updates necessary for adopting v2.x. Testing with 2.x with the current setup fails to start the container.
Also ported change to Trino.  
https://github.com/trinodb/trino/pull/24500
=> Update to oryd/hydra:v1.11.10 for OAuth2 testing

gateway-ha/pom.xml
Currently the three folders are never cleaned up and depending on your setup and build with switching branches and more this can lead to the wrong impression that things are working or not work as expected. 
This is a preliminary clean up to actually move the maven build parts for webapp into the webapp folder and will help for now .. 
#556 
=> Clean webapp output folders with Maven build

docker/docker-compose.yml, docs/installation.md, gateway-ha/pom.xml, gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/DataStoreConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/FlywayMigration.java, gateway-ha/src/main/resources/mysql/V1__create_schema.sql, gateway-ha/src/main/resources/postgresql/V1__create_schema.sql, gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestingJdbcConnectionManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/BaseTestDatabaseMigrations.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestDatabaseMigrationsMySql.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestDatabaseMigrationsPostgresql.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java, gateway-ha/src/test/resources/auth/auth-test-config.yml, gateway-ha/src/test/resources/auth/oauth-test-config.yml, gateway-ha/src/test/resources/test-config-template.yml, gateway-ha/src/test/resources/test-config-with-routing-template.yml, gateway-ha/src/test/resources/test-config-without-x-forwarded-template.yml
Add support for running mirations automatically with flyway on server startup. Since users may not want this, I added a config option to opt out of having the gateway process perform migrations. Migrations will only be performed by the gateway process if this config option is enabled.
This change will allow us to add backend DB support for Oracle in the future.
( X) Release notes are required. Please propose a release note for me.
```markdown
```
=> Use flyway to perform database migrations on startup

gateway-ha/src/test/java/io/trino/gateway/ha/persistence/BaseTestDatabaseMigrations.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestDatabaseMigrationsMySql.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestDatabaseMigrationsPostgreSql.java
=> Simplify database migration tests

docs/installation.md, gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/ProxyResponseConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyResponseHandler.java
`byte[]` cannot get logged. Changing it to actual `String` type for logging
```markdown
```
=> Convert byte array to string for logging in ProxyResponse

docs/routing-rules.md, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ForMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ForRouter.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ForProxy.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java
Adds config options for users to change timeouts when making external routing requests.
- #579 
```markdown
* Add support to handle HttpClient options for external routing group selector. ([#579](https://github.com/trinodb/trino-gateway/pull/580))
```
=> Add support to handle HttpClient options for external routing group selector

gateway-ha/src/main/java/io/trino/gateway/ha/router/StatementUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/resources/rules/routing_rules_trino_query_properties.yml
TrinoQueryProperties.getResourceGroupQueryType() called `toString` on an `Optional`. This unintended behavior produced output such as `"Optional[DATA_DEFINITION]"`, complicating rule writing for end users.
```markdown
* Fix TrinoQueryProperties.getResourceGroupQueryType()
```
=> Remove "Optional[]" from getResourceGroupQueryType string

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStats.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/TrinoStatus.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/response/BackendResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestObjectSerializable.java, webapp/src/components/cluster.tsx, webapp/src/types/cluster.d.ts
Display cluster health status on the cluster page
(x) Release notes are required. Please propose a release note for me.
=> Display cluster health status on cluster page

docs/installation.md, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJmxMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/JmxAttribute.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/JmxResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java, gateway-ha/src/test/resources/jvm-with-rmi.config, gateway-ha/src/test/resources/trino-config-with-rmi.properties
This pull request introduces a new `monitorType` for JMX-based monitoring in Trino Gateway. It includes documentation and configuration details for retrieving cluster information using specific JMX metrics.
- **Component:** JMX Monitoring in Trino Gateway
- **New Feature:** Added support for `monitorType: JMX` to enable cluster monitoring via JMX metrics.
- **Metrics Used:**
- `trino.execution:name=QueryManager`
- `trino.metadata:name=DiscoveryNodeManager`
- **Configuration Instructions:**
- Users can configure a username and password using `backendState`.
- Credentials must be valid across all clusters with `read` rights on `system_information`.
- **Example Configuration:**
```yaml
backendState:
username: "user"
password: "password"
clusterStatsConfiguration:
monitorType: JMX
```
( ) …
=> Add monitorType JMX

docs/development.md, gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestDatabaseMigrationsOracle.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManagerOracle.java
The Oracle test container runs very slowly on non x86 architectures, which causes tests to fail. These tests will be skipped unless they are running in Github Actions, on an x86_64, or explicitly enabled by setting the env var TG_RUN_ORACLE_TESTS=true.
(x ) This is not user-visible or is docs only, and no release notes are required.
=> Conditionally skip Oracle tests

docs/installation.md, docs/operation.md, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ActiveClusterMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayHealthCheckResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
Add two new health check API endpoints: `/trino-gateway/livez` and `/trino-gateway/readyz`.
`/trino-gateway/livez` always returns 200.
`/trino-gateway/readyz` returns 200 after the initial fetch from database and the first round of Trino cluster health check is completed. Otherwise, 503 will be returned.
```markdown
* Added API health endpoints `/trino-gateway/livez` and `/trino-gateway/readyz` for monitoring liveness and readiness. ({issue}`issuenumber`)
```
=> Add health check API endpoints

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJmxMonitor.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
Addressed feedback from @ebyhr from the origin PR. https://github.com/trinodb/trino-gateway/pull/472
```markdown
```
=> Cleanup monitorType JMX

docs/installation.md, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsInfoApiMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsMetricsMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/MonitorUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/MonitorConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java, gateway-ha/src/main/java/io/trino/gateway/ha/security/util/BasicCredentials.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
Add a monitor for the OpenMetrics endpoint. This populates the running and queued query metrics for active load balancing, and allows defining health using minimum and maximum values for arbitrary metrics.
Add a monitor for the `/metrics` endpoint. These metrics are equivalent to those under `v1/jmx`, however some organizations choose to standardize on OpenMetrics instead. 
A custom definition of backend health can be configured through the `metricMinimumValues` and `metricMaximumValues` settings in `monitorConfiguration`. Each of these takes `metricName, float` pairs. If the returned metric is below the min or greater than the max, the backend is considered unhealthy.
( ) Release notes are required. Please …
=> Add a monitor for the OpenMetrics endpoint

docs/gateway-api.md, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/HaGatewayConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/UIConfiguration.java, gateway-ha/src/main/java/io/trino/gateway/ha/domain/RoutingRule.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingRulesManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingAPI.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingRulesManager.java, gateway-ha/src/test/resources/rules/routing_rules_concurrent.yml, gateway-ha/src/test/resources/rules/routing_rules_update.yml, gateway-ha/src/test/resources/test-config-with-routing-rules-api.yml, webapp/src/api/webapp/login.ts, webapp/src/api/webapp/routing-rules.ts, webapp/src/components/layout.tsx, webapp/src/components/routing-rules.tsx, webapp/src/locales/en_US.ts, webapp/src/router.tsx, webapp/src/types/routing-rules.d.ts
1. Adding a way to display routing rules and also modify them from the UI
2. Minor change to show a user icon with a gear if user is ADMIN or a regular user icon if its a regular USER on the top right corner of the UI
3. Add config option to disable UI pages
```markdown
* 
```
=> Show and modify routing rules from the UI

docker/Dockerfile, docker/bin/health-check, docker/docker-compose.yml, docs/docker.md, docs/installation.md
Refactor `/opt/trino-gateway/config.yaml` to `/etc/trino-gateway/config.yaml`.
I made a mistake in #623. 
We should use the same file path in the Docker image and the [chart](https://github.com/trinodb/charts/blob/c1bacab5b15a8ece6186a40ddd676f725b20a93b/charts/gateway/templates/deployment.yaml#L88) to avoid confusion.
This also consist with Trino's config path `/etc/trino`.
```markdown
* [:warning: Breaking change:](#breaking) Change configuration file name in Docker image from 
`/opt/trino/gateway-ha-config.yml` to `/etc/trino-gateway/config.yaml`.
```
=> Update config file path in Docker image

webapp/src/components/cluster.tsx, webapp/src/components/resource-group.tsx, webapp/src/components/routing-rules.tsx, webapp/src/components/selector.tsx, webapp/src/locales/en_US.ts
Add UI popup messages after performing CRUD operations for Cluster, Resource Group, Selector and Routing Rules
=> Add UI popup messages for CRUD operations

gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
Remove trailing slash in proxyTo and externalUrl in create and update backend methods. Fixes https://github.com/trinodb/trino-gateway/issues/564
=> Remove trailing slash in proxyTo and externalUrl in create and update backend methods

docs/quickstart.md, docs/release-notes.md
Assemble the release notes for Trino Gateway 15 release and adjust rest of docs to version 15.
Release date is set to the planned date following our monthly release cadence.
* https://github.com/trinodb/charts/pull/315
* https://github.com/trinodb/charts/pull/310
* #622 ✅ rn ✅ docs
* #623 ✅ rn ✅ docs
* #632 ✅ rn ✅ docs
* #628 ✅ rn ✅ docs
* #617 ✅ rn ✅ docs
* #614 ✅ rn ✅ docs
* #570 ✅ rn ✅ docs
* #530 ✅ …
=> Add Trino Gateway 15 release notes

gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingDestination.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistoryDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/FileBasedRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryHistoryManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/StochasticRoutingManager.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/RouteToBackendResource.java, gateway-ha/src/main/resources/mysql/V2__add_routingGroup_to_query_history.sql, gateway-ha/src/main/resources/oracle/V2__add_routingGroup_to_query_history.sql, gateway-ha/src/main/resources/postgresql/V2__add_routingGroup_to_query_history.sql, gateway-ha/src/test/java/io/trino/gateway/TrinoGatewayRunner.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryCountBasedRouter.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestStochasticRoutingManager.java, webapp/src/components/history.tsx, webapp/src/types/history.d.ts
It is useful to show what routing group a request is being routed to because if two routing groups have the same `routedTo` url, it will show the wrong information on the history page
Old:
New:
=> Show RoutingGroup info in query history

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java
Trino Gateway supports disabling pages from the UI using uiConfiguration config https://trinodb.github.io/trino-gateway/gateway-api/#disable-routing-rules-ui
The webapp makes the call to get the list of disabled pages using the /webapp/getUIConfiguration endpoint.
This is called irrespective of whether an Admin has logged in or User because the pages disabled in the uiConfiguration are globally disabled.
However, currently only the ADMIN role is allowed to call /webapp/getUIConfiguration endpoint which results in "Login has expired, please login again" error messages whenever anyone with USER role logs in through the webapp.
Only the Admin is allowed to get the uiConfiguration based on https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/resource/ …
=> Allow USER role to get UI Configuration

gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/schema/RoutingDestination.java, gateway-ha/src/main/java/io/trino/gateway/ha/handler/schema/RoutingTargetResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/FileBasedRoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingGroupSelector.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/ExternalRouterResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingGroupResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingSelectorResponse.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/RouteToBackendResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java
This PR
Enhances the external routing service to support header modifications in requests. It allows the external routing service to set custom headers that will be applied to the original request before it's forwarded to the target backend.
closes #646 
- Added `setHeaders` field to `RoutingGroupExternalResponse` record to support header modifications
- Updated `ExternalRoutingGroupSelector` to handle header modifications from the external service
- Modified `RoutingTargetHandler` to apply the modified headers to the request
- Added comprehensive test coverage for header modification scenarios
The external routing service can now return headers that should be set in the request:
```json
{
"routingGroup": "test-group",
"errors": [],
"setHeaders": {
"x-trino-client-tags": ["etl"], …
```
=> Add Header Modification Support to External Routing Service

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayResource.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
As apart of efforts to improve telemetry as described in Issue https://github.com/trinodb/trino-gateway/issues/649, this PR adds logging for whenever a backend cluster is activated/deactivated. 
- built and ran locally
- confirmed logs appeared when calling de(activate) via curl call or changing deactivation status via the UI, e.g.:
```
2025-04-03T17:09:03.588-0700	INFO	http-worker-87	io.trino.gateway.ha.router.HaGatewayManager	Backend cluster trino-3 activation status changed to active=false (previous status: active=true).
```
- confirm error thrown if try to activate/deactivate non-existent backend
```
java.lang.IllegalStateException: No backend found with name: trino-4, could not activate
```
( ) Release …
=> Improve logging for backend cluster (de)activation

docs/operation.md, docs/routers.md, gateway-ha/config.yaml, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ActiveClusterMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/MonitorConfiguration.java, gateway-ha/src/test/resources/test-config-template.yml, gateway-ha/src/test/resources/test-config-with-routing-rules-api.yml, gateway-ha/src/test/resources/test-config-with-routing-template.yml, gateway-ha/src/test/resources/test-config-without-x-forwarded-template.yml
Use Airlift Duration in MonitorConfiguration
() Release notes are required. Please propose a release note for me.
(X) Release notes are required, with the following suggested text:
```markdown
* Fix monitor.taskDelaySeconds to use Airlift Duration
```
=> Use Airlift Duration in MonitorConfiguration

docs/routing-rules.md, gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/ExternalRouterResponse.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java
This PR makes the externalHeaders field optional in the external routing service response.
If omitted, the request proceeds without modifying headers.
It also updates the documentation to describe the externalHeaders feature, which allows external services to add or override request headers dynamically before forwarding.
related pull -  ({pull} #654 )
related issue -  ({issue} #699 )
```markdown
* Fix - external routing service requires the externalHeaders field in response. ({issue} #699 )
```
Do not need release note because issue is fixed before next release
=> Make externalHeaders optional in external service response

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/JdbcConnectionManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/persistence/TestJdbcConnectionManager.java
Fixing buildJdbcUrl to apply connection properties
fixing https://github.com/trinodb/trino-gateway/issues/650
```markdown
* Fix buildJdbcUrl to apply connection properties (https://github.com/trinodb/trino-gateway/issues/650)
```
=> Fix buildJdbcUrl to apply connection properties

gateway-ha/config.yaml, gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterMetricsStats.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterMetricsStatsExporter.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/MonitorConfiguration.java, gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterMetricsStatsExporter.java
As discussed in [Issue #649](https://github.com/trinodb/trino-gateway/issues/649) we would like to add a built-in activation status metric to Trino Gateway, to improve telemetry. This metric has a value of 1 if activated and a value of 0 if deactivated. The metric is populated with values polled directly from the database. Each cluster has it's own BackendClusterMetricsStats that can keep track of multiple metrics as we add in the future. When a backend cluster is added/deleted, an associated metric is registered/unregistered. 
To keep this information up to date, the backends table in the DB is polled every 30 seconds to check if any changes have been made. We can't rely on triggering a metrics registry refresh within the add/delete backend methods because only one instance gets this API …
=> Add cluster activation status metric and emit to v1/jmx

gateway-ha/src/main/java/io/trino/gateway/ha/router/HaGatewayManager.java
As apart of efforts to improve telemetry as described in Issue https://github.com/trinodb/trino-gateway/issues/649, PR [#672](https://github.com/trinodb/trino-gateway/pull/672) added logging for whenever a backend cluster is activated/deactivated. However, there's one log line that mixes up previous status and new status. This PR fixes it.
- built and ran locally
- deactivated/activated via UI and API call and confirmed status is accurate to activation status
```markdown
```
=> Fix mistake in deactivation status log

docs/routing-logic.md, gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java, gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistoryDao.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryHistoryManager.java, gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingManager.java, gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java, gateway-ha/src/main/resources/mysql/V3__add_externalUrl_to_query_history.sql, gateway-ha/src/main/resources/oracle/V3__add_externalUrl_to_query_history.sql, gateway-ha/src/main/resources/postgresql/V3__add_externalUrl_to_query_history.sql, gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestRoutingTargetHandler.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/BaseExternalUrlQueryHistoryTest.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestExternalUrlQueryHistoryMySql.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestExternalUrlQueryHistoryOracle.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestExternalUrlQueryHistoryPostgreSql.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingManagerExternalUrlCache.java, webapp/src/components/history.tsx, webapp/src/types/history.d.ts
Use external url field for query routing history page
The backendUrl used by Trino gateway may not be accessible for users, instead the external url field is used to indicate the hostname that's accessible by Trino users.  
For example, when hosted on Kubernetes, it's common to use [Kubernetes Service](https://kubernetes.io/docs/concepts/services-networking/service/) for inter apps communication like between Gateway and Trino clusters, in such cases the hostname used by Gateway would be something like `service-name.namespace.svc.cluster.local` which is only accessible from within the Kubernetes cluster. 
https://github.com/trinodb/trino-gateway/issues/81 is relevant issue with other discussion points.
(x) …
=> Use external url for query routing history

.github/workflows/ci.yml, .mvn/maven.config, .mvn/settings.xml, .mvn/wrapper/maven-wrapper.properties, gateway-ha/pom.xml, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestExternalUrlQueryHistoryOracle.java, pom.xml
Update project to enable using Njord for releaseing to Maven Central via the new required Sonatype portal.
* http://maveniverse.eu/docs/njord/migration/
* https://github.com/trinodb/trino/pull/26160
* https://github.com/trinodb/trino/pull/26156
=> Updates to enable new release method

gateway-ha/pom.xml
- Mina-core (org.apache.mina:mina-core):2.2.3
- Not directly referenced in the code
-  transitive dependency through org.apache.directory.api:api-all
- No direct evidence of usage
even on excluding from org.apache.directory.api:api-all and adding explicit 
<dependency>
<groupId>org.apache.mina</groupId>
<artifactId>mina-core</artifactId>
<version>2.2.4</version>
</dependency> 
[ERROR] Unused declared dependencies found:
[ERROR] org.apache.mina:mina-core:jar:2.2.4:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 31:31 min
[INFO] Finished at: 2025-06-25T16:58:59+05:30
[INFO] ------------------------------------------------------------- …
=> Exclude mina-core from Apache Directory LDAP API library

gateway-ha/src/main/java/io/trino/gateway/ha/security/LbAuthorizer.java
This PR refactors the logging logic in LbAuthorizer to ensure that log messages about user role identification (ADMIN, USER, API) are only written after the corresponding authorization check passes. Previously, the log messages could misleadingly indicate a user was identified as a role before the check was performed. Now, the logs clearly state whether a user is or is not identified as a given role, based on the actual result of the authorization check. The log message wording and style have also been improved for clarity and consistency.
=> Refactor LbAuthorizer logging: log role identification only after authorization check

docs/installation.md, docs/routers.md, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJmxMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsMetricsMonitor.java, gateway-ha/src/main/java/io/trino/gateway/ha/config/BackendStateConfiguration.java
As documented at https://trino.io/docs/current/security/tls.html#use-a-load-balancer-to-terminate-tls-https, when Trino is behind a loadbalancer or proxy like Trino Gateway, it's common that the TLS is terminated at Trino Gateway. 
Correspondingly when Trino Gateway forwards the request to Trino clusters, Gateway adds X-Forwarded-* headers in code [here](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java#L317). Relevant documentation is [here](https://trinodb.github.io/trino-gateway/installation/#trino-configuration) where users can optionally disable this by setting routing.addXForwardedHeaders to false.
This MR is to add the same Header while making [health check …
=> Add forward proto header configuration for cluster monitoring

docker/docker-compose.yml, gateway-ha/src/test/java/io/trino/gateway/TrinoGatewayRunner.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaWithRoutingRulesSingleBackend.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestNoXForwarded.java, gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManagerPostgresql.java, gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingAPI.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestAuthorization.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java, gateway-ha/src/test/java/io/trino/gateway/proxyserver/TestProxyRequestHandler.java
Recently trino gateway build steps have started to fail - https://github.com/trinodb/trino-gateway/actions/runs/16999454601/job/48197983562
Trinogateway always pulls latest postgres image which might result in unexpected failures. Its better to pin to a version
( X) This is not user-visible or is docs only, and no release notes are required.
=> Fix postgres image version

gateway-ha/src/main/java/io/trino/gateway/ha/domain/response/DistributionResponse.java, gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java, webapp/src/components/dashboard.tsx, webapp/src/locales/en_US.ts, webapp/src/types/dashboard.d.ts
Display the cluster healthy/unhealthy status count on the Dashboard
```markdown
* Fix some things.
```
=> Show cluster healthy/unhealthy status count on dashboard

gateway-ha/src/main/java/io/trino/gateway/proxyserver/MultiReadHttpServletRequest.java
- The return values of the function `isFinished` should be true only no bytes are available in the input stream to read
- `isReady` should always return true, since the inputstream should be ready all the time and never be false.
- Added methods to so that multiple bytes can be read for better performance.
@Chaho12 has idea on the issue with this code. @willmostly is the original author.
=> Enhance the MultiReadHttpServletRequest stream

.editorconfig, webapp/src/components/cluster.tsx, webapp/src/components/history.tsx
Added sort options for clusters based on name, queued query count and running query count.
Added filter option for routingGroup and sort options for routignGroup and submission time in query history page.
Clusters page header [3 new sort icons on Name, Queued, Running]:
History Page [Sort and Filter option on RoutingGroup] - 
( X) Release notes are required, with the following suggested text:
=> Add sorting for clusters and query history page columns

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJdbcMonitor.java, gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java
- __Change:__ Fix silent failure on invalid backend URL configuration
- __Impact:__ Fail-fast behavior with descriptive error messages
- __Lines:__ Replace `return clusterStats.build()` with `throw new IllegalArgumentException()`
- __Change:__ Replace `System.out.println()` with proper logging
- __Impact:__ Professional logging practices in test code
- __Lines:__ Add Logger import and replace print statement with `log.info()`
=> Improve code quality by addressing TODO comments
