docs/development.md

Mistakenly close branch 
- https://github.com/trinodb/trino-gateway/pull/23
Waiting for https://github.com/trinodb/trino-gateway/pull/25 branch to be merged

Update server command in development doc

---

docs/development.md

This updates the documentation to align with the Java update.

Update development instructions for Java 17

---

README.md
docs/design.md
docs/development.md
docs/gateway-api.md
docs/operation.md
docs/references.md
docs/resource-groups-api.md
docs/routing-rules.md
docs/security.md

https://github.com/trinodb/trino-gateway/issues/39

Ensure consistency in naming

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/RuleReloadingRoutingGroupSelector.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java

No review needed, no intent to merge - just testing CI failures that succeed locally.

Adding some logging to debug test failure

---

baseapp/pom.xml
baseapp/src/main/java/io/trino/gateway/baseapp/AppConfiguration.java
baseapp/src/main/java/io/trino/gateway/baseapp/AppModule.java
baseapp/src/main/java/io/trino/gateway/baseapp/BaseApp.java

Part of fixing https://github.com/trinodb/trino-gateway/issues/102
Using the Delombok refactor tool from IntelliJ

Remove Lombok usage in baseapp

---

gateway-ha/pom.xml
proxyserver/pom.xml
proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyHandler.java
proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServer.java
proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServerConfiguration.java
proxyserver/src/main/java/io/trino/gateway/proxyserver/ProxyServletImpl.java
proxyserver/src/main/java/io/trino/gateway/proxyserver/RequestFilter.java

Part of fixing https://github.com/trinodb/trino-gateway/issues/102
Related to #104 
Using the Delombok refactor tool from IntelliJ

Remove Lombok usage in proxyserver

---

gateway-ha/src/main/resources/template/header.ftl
gateway-ha/src/main/resources/template/login-form.ftl

Another task for https://github.com/trinodb/trino-gateway/issues/39

Fix app name in web UI

---

gateway-ha/pom.xml
pom.xml

From mixture of 5.5 and 5.4 to latest 5.8

Sync and upgrade Mockito deps

---

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOidcToken.java

Remove redundant catch block and add Language annotation.

Improve TestOidcToken

---

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStats.java
gateway-ha/src/main/java/io/trino/gateway/ha/resource/EntityEditorResource.java
gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayViewResource.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/BackendStateManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryHistoryManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/ResourceGroupsManager.java

This follows convention in Trino project. The new code is auto-generated by IntelliJ IDEA.

Simplify equals, hashCode and toString methods

---

gateway-ha/src/main/java/io/trino/gateway/ha/resource/TrinoResource.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java

Fix query param type in /trino/selector/read/{resourceGroupId}

---

docs/design.md

After the recent refactor the design doc was outdated. This is a light touch update only.
Please confirm @vishalya @willmostly @Chaho12

Clarify single module design doc

---

gateway-ha/src/main/java/io/trino/gateway/ha/module/ClusterStateListenerModule.java
gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/BackendStateManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/AuthorizationManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/RequestFilter.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestTrinoQueueLengthRoutingTable.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/LbLdapClientTest.java

Remove redundant code

---

docs/installation.md

Please review @willmostly @vishalya @Chaho12

Add clarification for Trino clusters

---

gateway-ha/pom.xml

Correct dropwizard dependencies

---

gateway-ha/pom.xml

Correct jakarta dependencies

---

gateway-ha/pom.xml

Correct test scope dependencies

---

gateway-ha/pom.xml

Correct jetty dependencies

---

gateway-ha/src/main/java/io/trino/gateway/baseapp/MetricRegistryModule.java

Use Jakarta Nonnull

---

gateway-ha/pom.xml

Correct jersey dependency

---

gateway-ha/pom.xml

Correct slf4j dependency

---

gateway-ha/pom.xml
pom.xml

Correct bouncycastle dependency

---

gateway-ha/pom.xml

Correct commons pool dependency

---

gateway-ha/pom.xml

Correct jackson dependency

---

gateway-ha/pom.xml

Fixes https://github.com/trinodb/trino-gateway/issues/213

Fix ViewRenderer missing dependency

---

gateway-ha/pom.xml
pom.xml

Closes https://github.com/trinodb/trino-gateway/issues/184

Update airbase to 149 and airlift to 240 and enable more checks

---

gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java

We shouldn't use `TestMethodOrder` as much as possible.

Avoid using TestMethodOrder in TestHaGatewayManager

---

gateway-ha/src/main/java/io/trino/gateway/ha/config/LdapConfiguration.java
gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/LbFormAuthManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/LbTokenUtil.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/wrapper/MultiReadHttpServletRequest.java
gateway-ha/src/test/java/io/trino/gateway/TrinoGatewayRunner.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbTokenUtil.java

Fix format and add missing final

---

.gitignore
docs/quickstart.md

- Udate quickstart doc to version ~5~ 6 with db checking code
- add var to gitignore in all directory hierarchy (for local dev) like trino https://github.com/trinodb/trino/commit/45bf374d6139406a83472ccd9314381a3280d955

Update quickstart doc

---

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/Selectors.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/SelectorsDao.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java

Relates to https://github.com/trinodb/trino-gateway/issues/229

Use JDBI for selectors

---

gateway-ha/pom.xml
gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java

Improve synchronization and minor refactoring in QueryCountBasedRouter.

Improve synchronization in QueryCountBasedRouter

---

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/RecordAndAnnotatedConstructorMapper.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ExactMatchSourceSelectors.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/GatewayBackend.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/QueryHistory.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroups.java
gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ResourceGroupsGlobalProperties.java

Refactor JDBI related classes.
Remove `@JdbiConstructor` and boilerplate codes.
Ensure all classes in dao/* are using the same coding style.

Refactor JDBI related classes

---

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/HealthCheckObserver.java
gateway-ha/src/main/java/io/trino/gateway/ha/resource/EntityEditorResource.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/RoutingManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryCountBasedRouter.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestStochasticRoutingManager.java

Fix typo in method names - `updateBackEndStats`, `updateBackEndHealth`
```markdown
* 
```

Fix typo in method names

---

webapp/src/components/cluster.tsx
webapp/src/components/layout.tsx
webapp/src/components/resource-group.tsx
webapp/src/components/selector.tsx

Remove console logging in web UI

---

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbLdapClient.java

This is the only class that doesn't follow the naming convention `TestXXXX`.

Rename LbLdapClientTest to TestLbLdapClient

---

.github/workflows/ci.yml

GitHub Action setup-java v3 -> v4
v4 is the latest version
```markdown
* 
```

setup-java v4

---

README.md

in readme file, as requested by @martint 

Shorten link to site

---

docs/release-notes.md

See title, I also closed out the issue now. 

Correct link for Helm chart release note

---

gateway-ha/src/main/java/io/trino/gateway/ha/resource/EntityEditorResource.java

When backend is updated on UI, we should not blindly set backend health to `true`
```markdown
* 
```

Set backend health to isActive() when it's modified on UI

---

docs/index.md

Fix links in the overview page: https://trinodb.github.io/trino-gateway/
```markdown
* 
```

Fix links in the overview page

---

docs/index.md

Notice an error and just improved the content of the whole list while I am editing.>

Improve wording on overview page

---

docs/resource-groups-api.md

People ask what is resource group in gateway every once in a while.
It must be confusing for new users, so I added some sentences to clarify
what resource group in gateway does.
- https://trinodb.slack.com/archives/CG9K9MX1V/p1710174886868119
- https://trinodb.slack.com/archives/CG9K9MX1V/p1714685877520219
```markdown
* 
```

Clarify the purpose of having resource group in gateway

---

docs/development.md

Add dev sync and maintainers

---

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java

Add `proxytarget` header to requests where `previousBackend` is found. Otherwise this line will return warning https://github.com/trinodb/trino-gateway/blob/d45c64f516062841339e9ce93e4675257e6e93e8/gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java#L154-L174
```markdown
* 
```

Add proxytarget header to query requests

---

pom.xml

Update airlift to 249

---

.github/workflows/ci.yml
docker/build.sh
helm/trino-gateway/templates/deployment.yaml
helm/trino-gateway/templates/service.yaml
helm/trino-gateway/values.yaml

Add Helm chart testing and fix https://github.com/trinodb/trino-gateway/issues/401
Add linting and a test install to CI. Bring Helm chart up to date with Airlift style configuration.
Improve Helm chart reliability

Update helm chart and add test to ci

---

webapp/.env.development

Replace Dropwizard's port 8090 with Airlift's port 8080.
```markdown
* 
```

Update UI development environment configuration

---

docs/routers.md
mkdocs.yml

Add the documentation for the routers and how to add a new router.
NA

Add doc for the current routers and steps to add a new one

---

gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java
webapp/src/components/dashboard.tsx
webapp/src/components/history.tsx
webapp/src/utils/time.ts

Improve the time of the UI distribution graph (#369)

---

helm/trino-gateway/templates/deployment.yaml

Fix indentation for deployment annotation

---

docs/installation.md

Add process forwarded info

---

docs/quickstart.md

Update quickstart doc 
- remove `server` parameter when launching server https://github.com/trinodb/trino-gateway/blob/main/docs/migration-to-airlift.md#jvm-startup-arguments
- remove unnecessary jvm options https://github.com/trinodb/trino-gateway/blob/main/docs/migration-to-airlift.md#jvm-options
```markdown
* 
```

Update quickstart doc to airlift

---

docs/development.md

as discussed in dev sync
Fixes #437

Improve release process docs

---

webapp/src/components/history.tsx

Fixes https://github.com/trinodb/trino-gateway/issues/370
```markdown
* 
```

Fix username reload in history page

---

docs/routing-rules.md

- By cleaning up source formatting
- Test with `mkdocs serve` locally if desired
- There are no content changes so review does not need to look at text (yes we need to improve text too but that can be done separately). We want to merge this soon to get live docs fixed.
See https://trinodb.slack.com/archives/C059KUNPTSP/p1725006443005719

Fix docs rendering issue

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoRequestUser.java

Improve UserInfo serialization to handle absent values.
Serialization of UserInfo was added at this PR
- https://github.com/trinodb/trino-gateway/pull/431
```markdown
```
As Manfred saids, this fixes feature within same release (11) so no need for release note

Improve UserInfo serialization to handle absent values

---

docs/installation.md
gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsInfoApiMonitor.java
gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsJdbcMonitor.java
gateway-ha/src/main/java/io/trino/gateway/ha/config/MonitorConfiguration.java
gateway-ha/src/main/java/io/trino/gateway/ha/module/ClusterStatsMonitorModule.java
gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java

Add timeout parameters for INFO_API and JDBC health checks.
(x ) Release notes are required, with the following suggested text:
Add timeout parameters for INFO_API and JDBC health checks.

Configure health check timeouts

---

docs/docs.md

Result from testing with Will.

Improve mkocs setup info

---

docs/installation.md

- Fixed documentation to specify `web-ui.authentication.type` as `FORM` instead of `PASSWORD`.
- Ensures users configure the Trino Gateway correctly for the `ui/api/stats` REST endpoint.
```markdown
* 
```

Fix documentation for UI_API

---

gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java

Fix deprecated warning in TestGatewayHaMultipleBackend

---

gateway-ha/src/main/java/io/trino/gateway/baseapp/BaseApp.java
gateway-ha/src/main/java/io/trino/gateway/ha/handler/RoutingTargetHandler.java
gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java

Inject `RoutingTargetHandler` instead of initializing it in `HaGatewayProviderModule`

Inject RoutingTargetHandler

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueryProperties.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java

Fix https://github.com/trinodb/trino-gateway/issues/484

Support Execute Immediate statement in TrinoQueryProperties

---

gateway-ha/pom.xml
webapp/pnpm-lock.yaml

- Node from v18.9.1 to latest LTS version v20.17.0
- pnpm from 8.6.12 to latest version 9.11.0
- Including all transitive dependencies
(x) No release notes entry needed.

Upgrade UI

---

pom.xml

Enable https://errorprone.info/bugpattern/UnusedMethod

Enable ErrorProne UnusedMethod

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/ExternalRoutingGroupSelector.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingGroupExternalBody.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/schema/RoutingGroupExternalResponse.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java

Remove redundant code from RoutingGroupExternalBody

Minor cleanup

---

gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbLdapClient.java

Minor cleanup in tests

---

gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaMultipleBackend.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaSingleBackend.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestGatewayHaWithRoutingRulesSingleBackend.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestNoXForwarded.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestObjectSerializable.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestTrinoResource.java
gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java
gateway-ha/src/test/java/io/trino/gateway/ha/handler/TestQueryIdCachingProxyHandler.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestHaGatewayManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryCountBasedRouter.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestQueryHistoryManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestResourceGroupsManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelectorExternal.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestStochasticRoutingManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestAuthorization.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthenticator.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbAuthorizer.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbFilter.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbLdapClient.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestLbTokenUtil.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/util/TestBasicCredentials.java

Follow Trino test guideline https://trino.io/docs/current/develop/tests.html

Follow test guideline

---

gateway-ha/src/main/java/io/trino/gateway/ha/handler/QueryIdCachingProxyHandler.java

Remove unused constant

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/StatementUtils.java

Move header place in StatementUtils

---

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/ClusterStatsHttpMonitor.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/util/ChainedAuthFilter.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java
pom.xml

Enable some ErrorProne rules

---

docs/index.md

Add link to OSDS video

---

docs/development.md
docs/docs.md
docs/installation.md
docs/migration-to-airlift.md
docs/operation.md
docs/routing-rules.md
docs/security.md

Add highlight hint for code blocks in docs

---

docs/routing-rules.md

Fix bullet point

---

docs/routing-rules.md

To enable better understanding of how to write routing rules.
Update from @andythsu s PR for pending status .. once I saw the file I just updated it all instead of just a small section.
Note for reviewers - this is all just grammar and wrapping and similar changes. Nothing fundamentally changed in terms of content and technical information.
#360 

Improve grammar and wording

---

gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java

https://github.com/trinodb/trino-gateway/pull/425#discussion_r1821587818

Remove redundant else

---

docs/release-notes.md

Fix source artifact links

---

gateway-ha/src/test/java/io/trino/gateway/TrinoGatewayRunner.java

Upgrade Trino version in test runner to the same version as the dependency in the pom.
Will allow us to test for http/2 and spooling protocol

Upgrade Trino version in test runner

---

gateway-ha/src/main/java/io/trino/gateway/ha/domain/request/QueryHistoryRequest.java
gateway-ha/src/main/java/io/trino/gateway/ha/resource/GatewayWebAppResource.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/HaQueryHistoryManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestObjectSerializable.java
webapp/src/components/history.tsx

Add `source` filter option to `History` page

Add Source filter to History page

---

gateway-ha/pom.xml

Still have to test but saw the upgrade is needed in the log... 

Upgrade to pnpm 9.14.2

---

gateway-ha/src/test/java/io/trino/gateway/TrinoGatewayRunner.java

Spooling protocol went final in 466 so this release is a good base for further development on support for it in Trino Gateway.
n.a.

Update Trino in runner class

---

docs/release-notes.md

Small oversight... needs fixing.

Update date for Trino Gateway 13 release

---

docs/release-notes.md

Without the empty line the whole things is rendered as a paragraph with * characters instead of a bulleted list.
na.

Fix changes list for release 7

---

README.md

Remove an extra space shown in hyperlink
```markdown
```

Clean up extra spaces in README.md

---

docs/installation.md
docs/migration-to-airlift.md

Update configuration file name in the Running Trino Gateway section to match the Configuration section
N/A
( ) Release notes are required, with the following suggested text:`

Update configuration file name to be consistent across sections

---

gateway-ha/pom.xml
gateway-ha/src/main/java/io/trino/gateway/ha/HaGatewayLauncher.java
gateway-ha/src/main/java/io/trino/gateway/ha/config/LdapConfiguration.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/RuleReloadingRoutingGroupSelector.java
gateway-ha/src/main/java/io/trino/gateway/ha/security/LbKeyProvider.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyResponseHandler.java
gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java
gateway-ha/src/test/java/io/trino/gateway/ha/TestingJdbcConnectionManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestSpecificDbResourceGroupsManager.java
pom.xml

Update airbase and airlift to the latest available. Code changes are all related to changes in the airlift API and new errorprone rules.
```markdown
* Update to airbase 211 and airlift 296
```

Update to latest airbase

---

gateway-ha/src/test/java/io/trino/gateway/ha/router/TestRoutingGroupSelector.java

#540 included changes to test method parameters. A new test using this method was merged after the last CI run of #540, so when #540 was merged the build broke.
(x ) This is not user-visible or is docs only, and no release notes are required.
```markdown
```

Fix compilation error

---

webapp/src/components/dashboard.tsx

Fix chart legend font color issue after changing the UI theme. Fixes https://github.com/trinodb/trino-gateway/issues/585

Fix chart legend font color issue after theme change

---

docs/release-notes.md

Improve info in release notes around Helm chart

---

.gitignore

Ignore MacOS directory files with git

---

webapp/README.md
webapp/src/locales/en_US.ts

to follow material UI patterns.. 
- Use sentence case consistently
- Avoid ! and .
- Remove "please" where not necessary

Improve UI labels

---

docs/assets/css/extra.css
docs/quickstart.md
docs/release-notes.md

Assemble the release notes for Trino Gateway 14 release and adjust rest of docs to version 14.
Currently we are reviewing more PR and will release after a few more are merged.
As a follow up we need to merge https://github.com/trinodb/charts/pull/289 for the Helm chart after this release is done.
* #563 ✅ rn ✅ docs
* #559 ✅ rn ✅ docs
* #567 ✅ rn ✅ docs
* #569 ✅ rn ✅ docs
* #572 ✅ rn ✅ docs
* #573 ✅ rn ✅ …

Add Trino Gateway 14 release notes

---

docker/docker-compose.yml

Fix #420
Remove version property from docker-compose.
See https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-and-name-top-level-elements

Remove version property from docker-compose

---

gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/NoopClusterStatsMonitor.java
gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java
gateway-ha/src/test/java/io/trino/gateway/ha/clustermonitor/TestClusterStatsMonitor.java

Fix #362
Fix #624 
Fix #625 
```markdown
* Fix bugs preventing the "Disable Health Checks" function from working.
```

Fix bug preventing the "Disable Health Checks" function from working.

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java

Fixing unnecessary calls to provideadhocbackend 
fixing #641 
(x ) This is not user-visible or is docs only, and no release notes are required.

fixing unnecessary call to provideadhocbackend

---

gateway-ha/src/main/java/io/trino/gateway/ha/module/QueryCountBasedRouterProvider.java
gateway-ha/src/main/java/io/trino/gateway/ha/module/StochasticRoutingManagerProvider.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/QueryCountBasedRouter.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/StochasticRoutingManager.java

Manual initialization is preventing us from using dependency injection. We should use Guice to manage the dependencies.

Let Guice manage dependencies in router modules

---

gateway-ha/src/main/java/io/trino/gateway/ha/router/MVELRoutingRule.java

Replace String concat with toStringHelper() in MVELRoutingRule
N/A

Replace String concat with toStringHelper() in MVELRoutingRule

---

docs/security.md

In the continuous effort to replace "backend" with "cluster" in the codebase.

Replace backend with cluster in security.md

---

gateway-ha/src/main/java/io/trino/gateway/ha/module/HaGatewayProviderModule.java

Remove unnecessary @Inject in HaGatewayProviderModule
```markdown
```

Remove unnecessary @Inject in HaGatewayProviderModule

---

gateway-ha/src/test/java/io/trino/gateway/ha/HaGatewayTestUtils.java
gateway-ha/src/test/java/io/trino/gateway/ha/security/TestOIDC.java
gateway-ha/src/test/resources/auth/auth-test-config.yml
gateway-ha/src/test/resources/auth/oauth-test-config.yml
gateway-ha/src/test/resources/test-config-template.yml
gateway-ha/src/test/resources/test-config-with-routing-rules-api.yml
gateway-ha/src/test/resources/test-config-with-routing-template.yml
gateway-ha/src/test/resources/test-config-without-x-forwarded-template.yml

Allow replacing test config with environment variable
```markdown
```

Allow replacing test config with environment variable

---

gateway-ha/pom.xml

PostgreSQL JDBC Driver (org.postgresql:postgresql):
Current version: 42.7.5
Recommended update: 42.7.7 or later
```markdown
* Fix some things.
```

Update PostgreSQL dependency

---

gateway-ha/src/main/java/io/trino/gateway/ha/persistence/dao/ExactMatchSourceSelectorsDao.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/HaResourceGroupsManager.java
gateway-ha/src/main/java/io/trino/gateway/ha/router/ResourceGroupsManager.java
gateway-ha/src/test/java/io/trino/gateway/ha/router/TestResourceGroupsManager.java

This method was called only from tests. 

Remove unused method

---

webapp/src/components/cluster.tsx

Update labels on Cluster page

---

gateway-ha/src/main/java/io/trino/gateway/ha/handler/ProxyUtils.java
gateway-ha/src/main/java/io/trino/gateway/proxyserver/ProxyRequestHandler.java
gateway-ha/src/main/resources/mysql/V4__update_query_text_column_type.sql
gateway-ha/src/main/resources/oracle/V4__update_query_text_column_type.sql
gateway-ha/src/main/resources/postgresql/V4__update_query_text_column_type.sql
gateway-ha/src/test/java/io/trino/gateway/proxyserver/TestProxyRequestHandler.java
webapp/package.json
webapp/pnpm-lock.yaml
webapp/src/components/cluster.tsx
webapp/src/components/history.tsx

This PR adds a feature to open the query text in a separate window to make the query text more readable.
1. Removes the 200 character limit for the query and truncation while storing in the database
2. Adds scripts to update the column query_text in query_history table to TEXT which can store longer strings.
3. Update the semi-ui version so that we can use the CodeHighlight feature - https://semi.design/en-US/plus/codehighlight
(X) Release notes are required, with the following suggested text:

Open query text in a separate window

---

docs/development.md

Remove `@willmostly` from maintainers

---

gateway-ha/pom.xml

```markdown
* Fix some things.
```

Fix the vulnerability in postgresql
